### ISSUE TITLE
看了一遍文档和代码和ThinkJS很像

### ISSUE THREAD

**Issue by ZQun** [thinkkoa/thinkkoa#2]
看了一遍文档和代码和ThinkJS很像

**Comment by richenlin** [comment]
有一些区别的，thinkjs2.0是自行实现核心封装的，没有基于koa，是一个类似rails的大而全的解决方案；

thinkjs3.0更像egg，特别是cluster及context封装扩展等方面。

当然，thinkjs和egg都是非常优秀的框架，他们的源码我都通读过，很多地方的解决思路和方法都借鉴了。
