### ISSUE TITLE
支持 MongoDB 了吗？

### ISSUE THREAD

**Issue by aov2005** [thinkkoa/thinkkoa#3]
看文档写着 beta ，不知道支持程度到怎样的呢

**Comment by richenlin** [comment]
数据库的支持是由thinkorm模块提供的。所以相关的问题可以发到[thinkorm](https://github.com/thinkkoa/thinkorm/issues)

目前，thinkorm对于mongodb的支持并不完整，仅仅支持普通的增删改查，group。不支持join，不支持关联操作（功能已经实现，单元测试未覆盖，存在bug）。当然您可以使用query原生语句操作，但意义不大。

主要的原因是我们团队的项目不管是thinkkoa还是thinkorm，都是项目驱动的，这个其他开源的项目不同。我们是公司项目需要使用某个技术栈，那么我们会进行实现和支持，thinkorm里面的mysql、postgresql等等都是如此，下一步公司的需求是oracle，我们可能会优先提供oracle的支持。

当然我们会不断的完善这些开源项目，我们也欢迎有开发能力的同学加入我们，一起来打造这个项目

**Comment by aov2005** [comment]
感谢回答
希望能跟 thinkjs 差异化，让开发者能有更多选择
