### ISSUE TITLE
npm start 之后不断自动重启

### ISSUE THREAD

**Issue by aov2005** [thinkkoa/thinkkoa#4]
![image](https://user-images.githubusercontent.com/6664259/28245689-3ba9656e-6a3f-11e7-889d-a34468f5d071.png)

提示
[ERROR] [ CallSite {},
  CallSite {},
  CallSite {},
  CallSite {},
  CallSite {},
  CallSite {},
  CallSite {} ] 
后不断重启，似乎是V8 多线程的问题

**Comment by richenlin** [comment]
请将您的操作系统、node版本、框架版本以及使用了那些中间件发给我们，方便定位错误原因

**Comment by aov2005** [comment]
操作系统 :  macOS 10.12.5
node版本: 7.6
框架版本 :  1.0.10

未使用中间件，直接think new demo && cd demo && cnpm i && npm start

**Comment by richenlin** [comment]
=_=||| 一直在6.x lts下跑测试和写代码，真没用用过7.x，稍后我启动个docker容器测试看看

**Comment by richenlin** [comment]
分别尝试了 ubuntu、centos，安装node.js7.6，cnpm，均未发现问题

难道是mac系统下特定场景出现，继续测试中

**Comment by richenlin** [comment]
![a47b004d-38ce-485c-8b08-8227b496a125](https://user-images.githubusercontent.com/6151439/28254207-2b4a2aa2-6add-11e7-93e1-16ace29ca36b.png)


我的mac可以运行。楼主重新install一次包试试，推荐使用：

```
sudo npm i -g nrm

nrm use cnpm

npm install
```

或者使用yarn：

```
sudo npm i -g yarn

yarn install
```

**Comment by aov2005** [comment]
![image](https://user-images.githubusercontent.com/6664259/28254993-ad655a6e-6ae4-11e7-8913-ae1cdcb4a84b.png)
![image](https://user-images.githubusercontent.com/6664259/28255000-b72a51f8-6ae4-11e7-9a5c-209c6de764a8.png)
还是一样

**Comment by richenlin** [comment]
ok,非常感谢。我需要跟踪下堆栈看能不能找出问题点。当然欢迎您也可以尝试

或者修改node_modules/thinkkoa/lib/think.js的 run：

分别逐步注释掉loader.loadConfig(), loader.loadMiddlewares() ,loader.loadModules(),看循环错误是否是loader文件加载出现的

**Comment by aov2005** [comment]
注释掉loader.loadConfig() 之后不会重启，提示加载中间件失败，分别注释其他两个框架都能运行，但是控制器访问报错，然后把注释清掉之后框架又正常运行了，很奇怪，是否是 全局的 node_modules 缓存问题?

**Comment by richenlin** [comment]
我知道了。loader内在require模块的时候，有一个清除模块缓存的机制，这个机制其实并非必要运行的，因为框架本身不需要刷新模块缓存，使用的supervisor来控制开发模式重启机制。

我调试下这里

**Comment by richenlin** [comment]
因为在我这里不复现（囧），跟踪堆栈和内存也是正常的。所以还得您帮忙配合调试：

修改 node_modules/thinkkoa/lib/util/loader.js:

```js
cleanCache(modulePath) {
        let module = require.cache[modulePath];
        // remove reference in module.parent
        if (module && module.parent) {
            module.parent.children.splice(module.parent.children.indexOf(module), 1);
        }
        require.cache[modulePath] = null;
    }
```

修改为： 

```js
cleanCache(modulePath) {
        try {
            // let module = require.cache[modulePath];
            // remove reference in module.parent
            // if (module && module.parent) {
            //     module.parent.children.splice(module.parent.children.indexOf(module), 1);
            // }
            // require.cache[modulePath] = null;
            delete require.cache[modulePath];
        } catch (e) { }
    }
```

**Comment by aov2005** [comment]
已修改，但是没抛出错误

发现问题了，再启动另一个  shell npm start 的时候就会出现，端口占用报错？

**Comment by richenlin** [comment]
端口占用错误控制台会打印：  [ERROR] Error: listen EADDRINUSE :::3000

这个是正常的，同一个端口仅可以监听一个node服务。在生产环境下需要启动集群的时候，一般是通过反向代理或者pm2来部署。

最后，再次感谢反馈。我们会发布一个新版本，修复此BUG

**Comment by richenlin** [comment]
[框架版本已经更新](http://thinkkoa.org/doc/index/doc/changelog.jhtml)
